shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('', views.cart_detail, name='cart_detail'),
]

shop/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('about_shop', views.about_shop, name='about_shop'),
    path('', views.product_list, name='product_list'),

]

shop/shopwebsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('orders/',include('orders.urls',namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/orders/models.py
from django.db import models

# Create your models here.
from shop.models import Product


class Order(models.Model):
    first_name=models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email=models.EmailField()
    address=models.CharField(max_length=250)
    postal_code=models.CharField(max_length=10)
    city=models.CharField(max_length=100)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now=True)
    paid=models.BooleanField(default=False)

    class Meta:
        ordering=('-created',)

    def __str__(self):
        return  f'Order {self.id}'

    def get_total_cost(self):
        return sum([item.get_cost() for item in self.items.all()])

class OrderItem(models.Model):
    order=models.ForeignKey(Order,
                            related_name='items',
                            on_delete=models.CASCADE)
    product=models.ForeignKey(Product,
                              related_name='order_items',
                              on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    count_product=models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price*self.count_product

shop/shop/models.py
from django.db import models

# Create your models here.

# модель Category -> таблиця shop_category
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField()

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        # db_table = 'category'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('shop:product_list_by_category', args=[self.slug])  # localhos:8000/slug


# клас Product -> таблиця shop_product
class Product(models.Model):
    category = models.ForeignKey('Category', related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created_date = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'name'),)
        # db_table='product'

    def __str__(self):
        return self.name

shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    count_product = forms.TypedChoiceField(label="Кількість",
                                           choices=PRODUCT_QUANTITY_CHOICES,
                                           coerce=int)
    update_count_product = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/orders/forms.py
from django import forms

from orders.models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

shop/cart/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     count_product=cd['count_product'],
                     update_count_product=cd['update_count_product'])
    else:
        cart.add(product=product)

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        #за ключем update_count_form додаємо в корзину форму для зміни кількості товару в корзині
        item['update_count_form'] = CartAddProductForm(initial={'count_product': item['count_product'],
                                                                'update_count_product': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shop/orders/views.py
from django.shortcuts import render
from cart.cart import Cart
from .forms import OrderCreateForm
from .models import OrderItem


def order_create(request):
    cart=Cart(request)
    if request.method=='POST':
        form=OrderCreateForm(request.POST)
        if form.is_valid():
            order=form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         count_product=item['count_product']
                                         )
            #Очищаємо корзину
            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order':order})
    else:
        form=OrderCreateForm()
    return render(request,
                          'orders/order/create.html',
                          {'cart':cart,'form':form})

shop/shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
# Create your views here.
from cart.forms import CartAddProductForm
from .models import Category,Product

def about_shop(request):
    return HttpResponse("Сторінка про магазин")

def product_list(request,category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.filter(available=True)
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        products=products.filter(category=category)

    paginator=Paginator(products,6)
    if 'page' in request.GET:
        page_num=request.GET['page']
    else:
        page_num=1
    page = paginator.get_page(page_num)
    print(page)
    print(page.object_list)
    print(page.number)
    return render(request,'shop/product/list.html',{
        'category':category,
        'categories':categories,
        'products':page.object_list,
        'page':page,
        })


def product_detail(request,id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

    # return render(request,'shop/product/detail.html',{'product':product})

shop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Корзина{% endblock %}
{% block content %}
<h2>Корзина з товарами</h2>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Зображення</th>
        <th>Назва товару</th>
        <th>Кількість</th>
        <th>Видалити</th>
        <th>Вартість за од.тов.</th>
        <th>Сума, грн</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <td>
            <a href="{% url 'shop:product_detail' id=item.product.id %}">
                <img src="{% if item.product.image %}{{ item.product.image.url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}">
            </a>
        </td>
        <td>{{ item.product.name }}</td>
        <td>
           <form action="{% url 'cart:cart_add' item.product.id %}" method="post">
               {% csrf_token %}
<!--               виведення окремо кожного поля форми із переданими значеннями за замовчуванням-->
               {{item.update_count_form.count_product}}
<!--               Наступне поле є прихованим (див. forms.py)-->
               {{item.update_count_form.update_count_product}}
                <input type="submit" value="Змінити">
            </form>
        </td>
        <td>
            <a href="{% url 'cart:cart_remove' item.product.id %}">Видалити</a>
        </td>
        <td>{{ item.price }} грн.</td>
        <td>{{ item.result_price }} грн.</td>
    </tr>
    {% endfor %}
    <tr>
        <td><b> Сума до оплати:</b></td>
        <td colspan="4"></td>
        <td><b>{{ cart.get_total_price }} грн.</b></td>
    </tr>
    </tbody>
</table>
<p>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="btn btn-primary">Продовжити покупки</a>
    <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Оформити замовлення</a>
</p>
{% endblock %}

shop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
     Order
{% endblock %}
{% block content %}
<h1> Оформлення замовлення</h1>
<div>
    <h3>Ваше замовлення</h3>
    <ul>
        {% for item in cart %}
        <li>
            {{ item.product.name}} - {{ item.count_product }} шт.
            <span> {{item.result_price}} грн.</span>
        </li>
        {% endfor %}
    </ul>
    <p>Загальна сума: {{cart.get_total_price}}</p>
</div>
<br>
<hr>
<form action="" method="post">
    {{ form.as_p}}
    <p><input type="submit" value="Send Order"></p>
    {% csrf_token %}

</form>
{% endblock %}

shop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
        Thanks
{% endblock %}
{% block content %}
<h1>Дякуємо!</h1>
<p>
    Ваше замовлення прийнято. Номер Вашого замовлення <b><i>{{order.id}}</i></b>
</p>
{% endblock %}

shop/shop/templates/shop/base.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Магазин {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:product_list' %}">Магазин</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'shop:product_list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:about_shop'%}">Про магазин</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="#">
                Контакти
              </a>
            </li>
          </ul>
            <a class="btn btn-primary" href="{% url 'cart:cart_detail' %}">
                <div > Корзина </div>
                <span>
                    {% with total_item=cart|length %}
                    {% if cart|length > 0 %}
                        {{total_item}}  вартістю {{cart.get_total_price}} грн.
                    {% else %}
                        0
                    {% endif %}
                    {% endwith%}
                </span>
            </a>

        </div>
      </div>
    </nav>
<div class="container">
    <div class="row m-2">
    {% block content %}{% endblock %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
</html>

shop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
     {{product.name}}
{% endblock %}
{% block content %}
<h2>{{product.name}}</h2>
<div>
    <img src="{% if product.image %} {{product.image.url}}{% else%}{% static 'img/no_image.png'%}{% endif %}">
    <h1> {{product.name}}</h1>
    <h2>
        <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
        <!--        <a href="{% url 'shop:product_list_by_category' product.category.slug %}">{{product.category }}</a>-->
    </h2>
    <p>{{ product.description }}</p>
    {{ product.description|linebreaks }}
    <p>{{ product.price }} грн.</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Додати до корзини">
    </form>
</div>


{% endblock %}

shop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}
category.name
{% else %}
Продукти
{% endif %}
{% endblock %}
{% block content %}
<div class="col-6 col-md-3">
    <h6>Категорії</h6>
    <ul>
        <li {% if not category %} class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">Всі</a>
        </li>
        {% for cat in categories %}
        <li>
            <a href="{{cat.get_absolute_url}}">{{cat.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="col-md-9">
    <div class="container">
        <div class="row m-2">
            {% for product in products %}
            <div class="col-4">
                 <div class="card m-2">
                    <a href="{% url 'shop:product_detail' product.id %}">
                        <img src="{% if product.image %} {{product.image.url}}{% else%}{% static 'img/no_image.png'%}{% endif %}"
                             class="card-img-top" >
                    </a>

                    <div class="card-body">
                        <a href="{% url 'shop:product_detail' product.id %}">
                            <h5 class="card-title"> {{product.name}}</h5>
                        </a>
                        <p class="card-text"> {{product.description}}</p>
                        <p class="card-text">{{product.price}} грн. </p>
                        <a href="{% url 'cart:cart_add' product.id %}" class="btn btn-primary">Додати</a>
                    </div>
                 </div>
            </div>
            {% endfor %}


        </div>
    </div>
    <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if page.has_previous %}
            <li class="page-item">
              <a  href="?page={{page.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">Попередня</span>
              </a>
            </li>
            {% endif%}
              <li class="page-item">
                  <span aria-hidden="true">
                      &nbsp; стор. {{page.number}} із {{page.paginator.num_pages}}&nbsp;
                  </span>
              </li>
            {% if page.has_next %}
              <li class="page-item">
              <a  href="?page={{page.next_page_number}}" aria-label="Next">
                <span aria-hidden="true"> Наступна </span>
              </a>
            </li>
              {% endif%}
          </ul>
        </nav>
</div>
{% endblock %}